id = "open-dylan"
name = "Open Dylan"
description = "Open Dylan language support with lsp-dylan LSP"
version = "0.0.1"
schema_version = 1
authors = ["Dylan Paulus <hello@dylanpaulus.com>"]
repository = "https://github.com/dylan/zed-open-dylan"

[grammars.dylan]
repository = "https://github.com/indika-dev/tree-sitter-dylan"
commit = "f49114a29f06b55853ba2ee96410973072b67d24"

[language_servers.dylan-lsp-server]
languages = ["Dylan"]
name = "dylan-lsp-server"
