// Tree-sitter grammar for Dylan (Open Dylan)
// Lexical grammar for syntax highlighting in Zed.
// Word lists derived from dylan-lang/vscode-dylan TextMate grammar (DRM spec).

const CONTROL = [
  "above",
  "afterwards",
  "begin",
  "below",
  "block",
  "by",
  "case",
  "cleanup",
  "else",
  "elseif",
  "end",
  "exception",
  "finally",
  "for",
  "from",
  "keyed-by",
  "if",
  "in",
  "otherwise",
  "select",
  "then",
  "to",
  "unless",
  "until",
  "using",
  "when",
  "while",
  "break",
  "error",
  "exit",
  "return",
  "signal",
];
const DEFINER = [
  "create",
  "define",
  "export",
  "import",
  "keyword",
  "let",
  "local",
  "method",
  "use",
  "class",
  "slot",
  "constant",
  "variable",
  "generic",
  "function",
  "module",
  "library",
  "macro",
  "handler",
];
const MODIFIER = [
  "sealed",
  "open",
  "abstract",
  "concrete",
  "primary",
  "free",
  "virtual",
  "inline",
  "inherited",
  "each-subclass",
  "dynamic",
  "singleton",
  "required",
];
const FUNCTION = [
  "abort",
  "abs",
  "add",
  "add!",
  "add-method",
  "add-new",
  "add-new!",
  "all-superclasses",
  "always",
  "any?",
  "applicable-method?",
  "apply",
  "aref",
  "aref-setter",
  "as",
  "as-lowercase",
  "as-lowercase!",
  "as-uppercase",
  "as-uppercase!",
  "ash",
  "backward-iteration-protocol",
  "ceiling",
  "cerror",
  "check-type",
  "choose",
  "choose-by",
  "complement",
  "compose",
  "concatenate",
  "concatenate-as",
  "condition-format-arguments",
  "condition-format-string",
  "conjoin",
  "copy-sequence",
  "curry",
  "default-handler",
  "dimension",
  "dimensions",
  "direct-subclasses",
  "direct-superclasses",
  "disjoin",
  "do",
  "do-handlers",
  "element",
  "element-setter",
  "empty?",
  "even?",
  "every?",
  "false-or",
  "fill!",
  "find-key",
  "find-method",
  "first",
  "first-setter",
  "floor",
  "forward-iteration-protocol",
  "function-arguments",
  "function-return-values",
  "function-specializers",
  "gcd",
  "generic-function-mandatory-keywords",
  "generic-function-methods",
  "head",
  "head-setter",
  "identity",
  "initialize",
  "instance?",
  "integral?",
  "intersection",
  "key-sequence",
  "key-test",
  "last",
  "last-setter",
  "lcm",
  "limited",
  "list",
  "logand",
  "logbit?",
  "logior",
  "lognot",
  "logxor",
  "make",
  "map",
  "map-as",
  "map-into",
  "max",
  "member?",
  "merge-hash-codes",
  "min",
  "modulo",
  "negative",
  "negative?",
  "next-method",
  "object-class",
  "object-hash",
  "odd?",
  "one-of",
  "pair",
  "pop",
  "pop-last",
  "positive?",
  "push",
  "push-last",
  "range",
  "rank",
  "rcurry",
  "reduce",
  "reduce1",
  "remainder",
  "remove",
  "remove!",
  "remove-duplicates",
  "remove-duplicates!",
  "remove-key!",
  "remove-method",
  "replace-elements!",
  "replace-subsequence!",
  "restart-query",
  "return-allowed?",
  "return-description",
  "return-query",
  "reverse",
  "reverse!",
  "round",
  "row-major-index",
  "second",
  "second-setter",
  "shallow-copy",
  "size",
  "size-setter",
  "slot-initialized?",
  "sort",
  "sort!",
  "sorted-applicable-methods",
  "subsequence-position",
  "subtype?",
  "table-protocol",
  "tail",
  "tail-setter",
  "third",
  "third-setter",
  "type-error-expected-type",
  "type-error-value",
  "type-for-copy",
  "type-union",
  "union",
  "values",
  "vector",
  "zero?",
];

module.exports = grammar({
  name: "dylan",
  word: ($) => $.identifier,
  extras: ($) => [/\s/, $.comment_line, $.comment_block],
  rules: {
    source_file: ($) => repeat($._token),

    _token: ($) =>
      choice(
        $.control_keyword,
        $.definer_keyword,
        $.modifier_keyword,
        $.builtin_function,
        $.type,
        $.string,
        $.raw_string,
        $.symbol,
        $.keyword_symbol,
        $.escaped_name,
        $.character,
        $.boolean,
        $.hash_word,
        $.number,
        $.operator,
        $.identifier,
        $.punctuation,
      ),

    control_keyword: ($) => choice(...CONTROL),
    definer_keyword: ($) => choice(...DEFINER),
    modifier_keyword: ($) => choice(...MODIFIER),
    builtin_function: ($) => choice(...FUNCTION),

    // <foo>, <my-class> : Dylan type-naming convention
    type: ($) => token(/<[a-zA-Z][a-zA-Z0-9_\-!?*]*>/),

    comment_line: ($) => token(seq("//", /[^\n]*/)),
    comment_block: ($) => token(seq("/*", /[^*]*\*+([^/*][^*]*\*+)*/, "/")),

    string: ($) => token(/"([^"\\]|\\.)*"/),
    raw_string: ($) => token(/#[rR]"([^"\\]|\\.)*"/),
    symbol: ($) => token(/#"([^"\\]|\\.)*"/),
    // name: keyword-argument / symbol literal
    keyword_symbol: ($) => token(/[a-zA-Z][a-zA-Z0-9_\-]*:/),
    // \== \+ \object-class : a name/operator referenced as a value
    escaped_name: ($) => token(/\\[a-zA-Z0-9!?*+\-\/<>=~^&|]+/),
    character: ($) => token(/'([^'\\]|\\.)'/),
    boolean: ($) => token(/#[tf]/),
    // #rest #key #all-keys #next #include : parameter / call keywords
    hash_word: ($) => token(/#(all-keys|rest|key|next|include)/),

    number: ($) =>
      token(
        choice(
          /#[xX][0-9a-fA-F_]+/,
          /#[oO][0-7_]+/,
          /#[bB][01_]+/,
          /[+-]?([0-9][0-9_]*(\.[0-9_]*)?|\.[0-9_]+)([esdxESDX][+-]?[0-9_]+)?/,
        ),
      ),

    operator: ($) =>
      token(
        choice(
          "##",
          ":=",
          "==",
          "~==",
          "<=",
          ">=",
          "=>",
          "::",
          "~=",
          "~",
          "=",
          "<",
          ">",
          "+",
          "-",
          "*",
          "/",
          "&",
          "|",
          "^",
          ".",
          "?",
          ":",
        ),
      ),

    punctuation: ($) =>
      token(choice("#(", "#[", "(", ")", "[", "]", "{", "}", ",", ";")),

    identifier: ($) => token(/[a-zA-Z_$%*][a-zA-Z0-9_\-*]*[!?]?/),
  },
});
