name = "Dylan"
grammar = "dylan"
path_suffixes = ["dylan", "lid"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
language_servers = ["dylan-lsp-server"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
]
